[package]
name = "bps-fuse"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
crc = "1.8.1"
fuse_mt = "0.5.0"
inotify = "0.8"
libc = "0.2"
log = "0.4"
num_enum = "0.5.0"
pretty_env_logger = "0.4"
time = "0.1"
