[package]
name = "fuse-bps-softpatch"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
crc = "1.8.1"
fuse_mt = "0.5.0"
libc = "0.2"
notify = "5.0.0-pre.2"
time = "0.1"
